//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbolMenu
    {
        public System.Guid IdArbolMenu { get; set; }
        public Nullable<System.Guid> IdArbolMenuPadre { get; set; }
        public string Descripcion { get; set; }
        public string IdArticulo { get; set; }
        public bool Expand { get; set; }
        public string RutaImagen { get; set; }
        public string Condicion { get; set; }
        public string iconSrc { get; set; }
        public Nullable<bool> Largo { get; set; }
        public Nullable<bool> Ancho { get; set; }
        public Nullable<bool> Color { get; set; }
        public Nullable<bool> Complemento { get; set; }
        public bool WebEstilo { get; set; }
    }
}
