//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoDetalle
    {
        public int id { get; set; }
        public Nullable<int> idEncabezado { get; set; }
        public Nullable<double> renglon { get; set; }
        public string articulo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public Nullable<double> Descuento { get; set; }
    
        public virtual CarritoEncabezado CarritoEncabezado { get; set; }
    }
}
