//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDVentaV33
    {
        public string OrdenExportacion { get; set; }
        public int ID { get; set; }
        public string VentaSerie { get; set; }
        public string VentaFolio { get; set; }
        public Nullable<System.DateTime> VentaFechaRegistroV33 { get; set; }
        public string FormaPagoV33 { get; set; }
        public string VentaCondicion { get; set; }
        public Nullable<double> VentaSubTotal { get; set; }
        public Nullable<double> VentaDescuentoImporte { get; set; }
        public string MonedaV33 { get; set; }
        public Nullable<double> VentaTipoCambio { get; set; }
        public Nullable<double> VentaTotal { get; set; }
        public string TipoComprobanteV33 { get; set; }
        public string MetodoPagoV33 { get; set; }
        public string LugarExpedicionEmpresaV33 { get; set; }
        public string LugarExpedicionSucursalV33 { get; set; }
        public string EmpresaNombre { get; set; }
        public string EmpresaRFC { get; set; }
        public string EmpresaRegimenFiscalV33 { get; set; }
        public string SucursalNombre { get; set; }
        public string SucursalRFC { get; set; }
        public string SucursalRegimenFiscalV33 { get; set; }
        public string ClaveUsoCFDIV33 { get; set; }
        public string CteResidenciaFiscalV33 { get; set; }
        public string CteNumRegIdTribV33 { get; set; }
        public string ClienteNombre { get; set; }
        public string ClienteRFC { get; set; }
        public string VentaEstatusCancelacion { get; set; }
        public string VentaTipoDocumento { get; set; }
        public string VentaImporteLetra { get; set; }
        public string VentaOrdenCompra { get; set; }
        public Nullable<System.DateTime> VentaOrdenCompraFecha { get; set; }
        public Nullable<int> CFDnoAprobacion { get; set; }
        public string VentaEntregaRecibo { get; set; }
        public Nullable<System.DateTime> VentaEntregaReciboFecha { get; set; }
        public string ClienteGLN { get; set; }
        public string CteDeptoClave { get; set; }
        public string EmpresaGLN { get; set; }
        public string ClienteProveedorID { get; set; }
        public string ClienteDireccion { get; set; }
        public string ClienteLocalidad { get; set; }
        public string ClienteCodigoPostal { get; set; }
        public string VentaMoneda { get; set; }
        public string VentaTipoPago { get; set; }
        public int CondicionDiasVencimiento { get; set; }
        public string VentaDescuentoGlobalClave { get; set; }
        public Nullable<double> VentaPorcentajeDescuentoGlobal { get; set; }
    }
}
