//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CteEnviarA
    {
        public string Cliente { get; set; }
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string EntreCalles { get; set; }
        public string Plano { get; set; }
        public string Observaciones { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Zona { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public bool PedirTono { get; set; }
        public string Contacto1 { get; set; }
        public string Contacto2 { get; set; }
        public string Extencion1 { get; set; }
        public string Extencion2 { get; set; }
        public string eMail1 { get; set; }
        public string eMail2 { get; set; }
        public string FormaEnvio { get; set; }
        public string ZonaImpuesto { get; set; }
        public string Agente { get; set; }
        public string Clase { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> UltimoCambio { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public string Mensaje { get; set; }
        public bool Logico1 { get; set; }
        public bool Logico2 { get; set; }
        public bool Logico3 { get; set; }
        public string ListaPreciosEsp { get; set; }
        public string Proyecto { get; set; }
        public string Condicion { get; set; }
        public string Descuento { get; set; }
        public string ModificarVencimiento { get; set; }
        public string Categoria { get; set; }
        public string Grupo { get; set; }
        public string Familia { get; set; }
        public Nullable<bool> TieneMovimientos { get; set; }
        public string Delegacion { get; set; }
        public string Ruta { get; set; }
        public string Contrasena { get; set; }
        public byte[] SincroID { get; set; }
        public Nullable<int> SincroC { get; set; }
        public string Clave { get; set; }
        public Nullable<int> SucursalEmpresa { get; set; }
        public string PersonalCobrador { get; set; }
        public string Almacen { get; set; }
        public string AlmacenVtasConsignacion { get; set; }
        public Nullable<bool> eMailAuto { get; set; }
        public string wMovVentas { get; set; }
        public string TipoEmpaque { get; set; }
        public string Unidad { get; set; }
        public string Cadena { get; set; }
        public string DireccionNumeroInt { get; set; }
        public string Encargado { get; set; }
        public string DireccionNumero { get; set; }
        public string GLN { get; set; }
        public string TMEws_id { get; set; }
        public string TMEws_status { get; set; }
        public string FiscalRegimen { get; set; }
        public string FiscalZona { get; set; }
        public string TipoProceso { get; set; }
        public string TipoComite { get; set; }
        public string IdContabilidad { get; set; }
        public string ClaveEntidad { get; set; }
        public string Ambito { get; set; }
        public string EntidadIdContabilidad { get; set; }
        public string InstitucionFin { get; set; }
        public string FormaPago { get; set; }
        public string Cuenta { get; set; }
        public string TMERFC2 { get; set; }
    }
}
