//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    
    public partial class GetArticulo_Result1
    {
        public string Articulo { get; set; }
        public string Descripcion1 { get; set; }
        public string tmecolor { get; set; }
        public string TMELargo { get; set; }
        public string TMEAncho { get; set; }
        public string tmeclasflam { get; set; }
    }
}
