//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoMedidasEstandar
    {
        public int id { get; set; }
        public string Linea { get; set; }
        public string Color { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> C240 { get; set; }
        public Nullable<int> C300 { get; set; }
        public Nullable<int> C360 { get; set; }
        public Nullable<int> B240 { get; set; }
        public Nullable<int> B360 { get; set; }
        public Nullable<int> B90240 { get; set; }
        public Nullable<int> Total { get; set; }
        public string cliente { get; set; }
    }
}
