//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    
    public partial class sp_GetFacturasPorPagarCliente_Result1
    {
        public Nullable<int> VentaId { get; set; }
        public string movid { get; set; }
        public string Orden_de_compra { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<int> DiasMoratorios { get; set; }
    }
}
