//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    
    public partial class spPEdidoAfectado_Result2
    {
        public int ID { get; set; }
        public string Mov { get; set; }
        public string MovID { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Concepto { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string OrdenCompra { get; set; }
        public string Condicion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<System.DateTime> FechaRequerida { get; set; }
        public string EnviarANombre { get; set; }
        public Nullable<bool> Hay_Prod { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<decimal> Suritdo { get; set; }
    }
}
