//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMEPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaD
    {
        public int ID { get; set; }
        public double Renglon { get; set; }
        public int RenglonSub { get; set; }
        public Nullable<int> RenglonID { get; set; }
        public string RenglonTipo { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string SubCuenta { get; set; }
        public Nullable<double> Precio { get; set; }
        public string DescuentoTipo { get; set; }
        public Nullable<decimal> DescuentoLinea { get; set; }
        public Nullable<double> Impuesto1 { get; set; }
        public Nullable<double> Impuesto2 { get; set; }
        public string DescripcionExtra { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Paquete { get; set; }
        public string ContUso { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public string Aplica { get; set; }
        public string AplicaID { get; set; }
        public Nullable<double> CantidadPendiente { get; set; }
        public Nullable<double> Flotante1 { get; set; }
        public Nullable<double> CantidadReservada { get; set; }
        public Nullable<double> CantidadCancelada { get; set; }
        public Nullable<double> CantidadOrdenada { get; set; }
        public Nullable<double> CantidadA { get; set; }
        public string Unidad { get; set; }
        public Nullable<double> Factor { get; set; }
        public string SustitutoArticulo { get; set; }
        public string SustitutoSubCuenta { get; set; }
        public Nullable<System.DateTime> FechaRequerida { get; set; }
        public string Instruccion { get; set; }
        public Nullable<decimal> Impuesto3 { get; set; }
        public Nullable<double> CantidadInventario { get; set; }
        public Nullable<double> UltimoReservadoCantidad { get; set; }
        public Nullable<System.DateTime> UltimoReservadoFecha { get; set; }
        public string Agente { get; set; }
        public Nullable<int> Departamento { get; set; }
        public int Sucursal { get; set; }
        public int SucursalOrigen { get; set; }
        public Nullable<decimal> DescuentoImporte { get; set; }
        public string PoliticaPrecios { get; set; }
        public byte[] SincroID { get; set; }
        public Nullable<int> SincroC { get; set; }
        public string AutoLocalidad { get; set; }
        public Nullable<int> UEN { get; set; }
        public string Espacio { get; set; }
        public string HoraRequerida { get; set; }
        public Nullable<double> CantidadAlterna { get; set; }
        public string PrecioMoneda { get; set; }
        public Nullable<double> PrecioTipoCambio { get; set; }
        public Nullable<double> CantidadEmbarcada { get; set; }
        public string Estado { get; set; }
        public Nullable<double> ServicioNumero { get; set; }
        public Nullable<int> AgentesAsignados { get; set; }
        public string AFArticulo { get; set; }
        public string AFSerie { get; set; }
        public Nullable<bool> ExcluirPlaneacion { get; set; }
        public Nullable<bool> Anexo { get; set; }
        public Nullable<decimal> CostoActividad { get; set; }
        public string Codigo { get; set; }
        public Nullable<bool> ExcluirISAN { get; set; }
        public Nullable<double> PrecioSugerido { get; set; }
        public Nullable<int> EnviarA { get; set; }
        public Nullable<decimal> CostoUEPS { get; set; }
        public Nullable<decimal> CostoPEPS { get; set; }
        public Nullable<decimal> UltimoCosto { get; set; }
        public Nullable<decimal> PrecioLista { get; set; }
        public string Posicion { get; set; }
        public Nullable<decimal> AjusteCosteo { get; set; }
        public Nullable<int> DepartamentoDetallista { get; set; }
        public Nullable<double> CantidadObsequio { get; set; }
        public Nullable<bool> PresupuestoEsp { get; set; }
        public string Procesadoid { get; set; }
        public string TipoRetencion1 { get; set; }
        public string TipoRetencion2 { get; set; }
        public string TipoRetencion3 { get; set; }
        public Nullable<decimal> Costoestandar { get; set; }
        public string ContUso2 { get; set; }
        public string ContUso3 { get; set; }
        public string TipoImpuesto1 { get; set; }
        public string TipoImpuesto2 { get; set; }
        public string TipoImpuesto3 { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> CostoReposicion { get; set; }
        public string OrdenCompra { get; set; }
        public Nullable<bool> AnticipoFacturado { get; set; }
        public string AnticipoMoneda { get; set; }
        public Nullable<double> AnticipoTipoCambio { get; set; }
        public Nullable<double> AnticipoRetencion { get; set; }
        public Nullable<double> Retencion1 { get; set; }
        public Nullable<double> Retencion2 { get; set; }
        public Nullable<double> Retencion3 { get; set; }
        public string tarima { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public Nullable<int> Ofertaid { get; set; }
        public string ProveedorRef { get; set; }
        public string Transferira { get; set; }
        public string ArtEstatus { get; set; }
        public string ArtSituacion { get; set; }
        public string Abc { get; set; }
    }
}
